<?php
declare(strict_types=1);

/** User Registration & Trainee portal layout + dashboard components (scoped to body.portal-page). */
function renderPortalStyles(): void
{
    static $done = false;
    if ($done) {
        return;
    }
    $done = true;
    echo '<style id="cybeorch-portal">'
        . ':root{--cyber-dark:#050b18;--cyber-navy:#0a1628;--cyber-blue:#0f3460;--cyber-accent:#00d4ff;--cyber-green:#00ff88;--cyber-orange:#ff6b35;--cyber-muted:#7a8fa6;--cyber-text:#e0e8f0;--cyber-border:rgba(0,212,255,0.2);--cyber-card:rgba(15,52,96,0.35);--sidebar-w:260px;}'
        . 'html,body{margin:0;padding:0;}'
        . 'body.portal-page{background:var(--cyber-dark);color:var(--cyber-text);font-family:\'DM Sans\',sans-serif;overflow-x:hidden;min-height:100vh;}'
        . 'body.portal-page::before{content:\'\';position:fixed;inset:0;background-image:linear-gradient(rgba(0,212,255,0.02) 1px,transparent 1px),linear-gradient(90deg,rgba(0,212,255,0.02) 1px,transparent 1px);background-size:60px 60px;pointer-events:none;z-index:0;}'
        . 'body.portal-page .sidebar{position:fixed;top:0;left:0;width:var(--sidebar-w);height:100vh;height:100dvh;background:var(--cyber-navy);border-right:1px solid var(--cyber-border);z-index:1040;display:flex;flex-direction:column;overflow-y:auto;overflow-x:hidden;}'
        . 'body.portal-page .main{margin:0 0 0 var(--sidebar-w);padding:0;width:calc(100% - var(--sidebar-w));min-height:100vh;min-height:100dvh;display:flex;flex-direction:column;position:relative;z-index:1;box-sizing:border-box;}'
        . 'body.portal-page .topbar{flex-shrink:0;margin:0;padding:.75rem 1.25rem;background:rgba(10,22,40,.92);border-bottom:1px solid var(--cyber-border);display:flex;align-items:center;justify-content:space-between;flex-wrap:nowrap;gap:.75rem;position:sticky;top:0;z-index:50;backdrop-filter:blur(10px);}'
        . 'body.portal-page .page-title{font-family:\'Rajdhani\',sans-serif;font-size:clamp(1.15rem,3vw,1.4rem);font-weight:700;margin:0;line-height:1.2;flex:1 1 auto;min-width:0;}'
        . 'body.portal-page .topbar-actions{display:flex;align-items:center;gap:.75rem;flex:0 0 auto;width:auto!important;margin:0;}'
        . 'body.portal-page .content{flex:1 1 auto;margin:0;padding:1.25rem 1.5rem 1.5rem;width:100%;max-width:100%;box-sizing:border-box;}'
        . 'body.portal-page .content>.row:last-child{margin-bottom:0;}'
        . 'body.portal-page .sidebar-logo{padding:1.25rem 1.5rem;border-bottom:1px solid var(--cyber-border);flex-shrink:0;}'
        . 'body.portal-page .sidebar-logo-text{font-size:1.5rem;text-decoration:none;display:inline-block;}'
        . 'body.portal-page .sidebar-user{padding:1rem 1.25rem;border-bottom:1px solid var(--cyber-border);display:flex;align-items:center;gap:.75rem;flex-shrink:0;}'
        . 'body.portal-page .user-avatar{width:42px;height:42px;border-radius:50%;background:linear-gradient(135deg,var(--cyber-accent),var(--cyber-blue));display:flex;align-items:center;justify-content:center;font-weight:700;color:var(--cyber-dark);flex-shrink:0;font-size:.85rem;}'
        . 'body.portal-page .user-info-name{font-size:.88rem;font-weight:500;}'
        . 'body.portal-page .user-info-email{font-size:.75rem;color:var(--cyber-muted);word-break:break-all;}'
        . 'body.portal-page .sidebar-nav{flex:1 1 auto;padding:.75rem 0;overflow-y:auto;min-height:0;}'
        . 'body.portal-page .nav-section{padding:.5rem 1.25rem .2rem;font-size:.7rem;color:var(--cyber-muted);text-transform:uppercase;letter-spacing:1.5px;font-weight:600;}'
        . 'body.portal-page .sidebar-link{display:flex;align-items:center;gap:.75rem;padding:.6rem 1.25rem;color:var(--cyber-muted);text-decoration:none;font-size:.88rem;border-left:3px solid transparent;transition:background .15s,color .15s;}'
        . 'body.portal-page .sidebar-link i{width:20px;text-align:center;flex-shrink:0;}'
        . 'body.portal-page .sidebar-link:hover,body.portal-page .sidebar-link.active{color:var(--cyber-accent);background:rgba(0,212,255,.06);border-left-color:var(--cyber-accent);}'
        . 'body.portal-page .badge-count{margin-left:auto;background:var(--cyber-accent);color:var(--cyber-dark);font-size:.7rem;padding:1px 7px;border-radius:10px;font-weight:700;}'
        . 'body.portal-page .wallet-widget{margin:.75rem 1rem 1rem;flex-shrink:0;background:linear-gradient(135deg,rgba(0,212,255,.15),rgba(0,255,136,.08));border:1px solid var(--cyber-border);border-radius:10px;padding:1rem;}'
        . 'body.portal-page .wallet-balance{font-family:\'Rajdhani\',sans-serif;font-size:1.65rem;font-weight:700;color:var(--cyber-green);line-height:1.1;}'
        . 'body.portal-page .card-panel{background:var(--cyber-card);border:1px solid var(--cyber-border);border-radius:12px;padding:1.25rem;margin-bottom:1rem;}'
        . 'body.portal-page .btn-cyber{background:var(--cyber-accent);color:#050b18;border:none;padding:.6rem 1.2rem;border-radius:8px;font-weight:700;text-decoration:none;display:inline-block;cursor:pointer;}'
        . 'body.portal-page .btn-cyber:hover{background:var(--cyber-green);color:#050b18;}'
        . 'body.portal-page .form-control{background:rgba(255,255,255,.06)!important;border:1px solid var(--cyber-border)!important;color:var(--cyber-text)!important;border-radius:8px!important;}'
        . 'body.portal-page .flex-1{flex:1 1 auto;min-width:0;}'
        . 'body.portal-page .stat-card{background:var(--cyber-card);border:1px solid var(--cyber-border);border-radius:12px;padding:1.15rem 1.25rem;transition:border-color .2s,transform .2s;height:100%;min-width:0;}'
        . 'body.portal-page .stat-card:hover{border-color:var(--cyber-accent);transform:translateY(-2px);}'
        . 'body.portal-page .stat-icon{width:44px;height:44px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:1.1rem;margin-bottom:.65rem;}'
        . 'body.portal-page .stat-value{font-family:\'Rajdhani\',sans-serif;font-size:clamp(1.4rem,4vw,1.85rem);font-weight:700;line-height:1.1;}'
        . 'body.portal-page .stat-label{font-size:.82rem;color:var(--cyber-muted);margin-top:.25rem;}'
        . 'body.portal-page .stat-change{font-size:.78rem;margin-top:.25rem;}'
        . 'body.portal-page .stat-change.up{color:var(--cyber-green);}'
        . 'body.portal-page .section-card{background:var(--cyber-card);border:1px solid var(--cyber-border);border-radius:12px;padding:1.25rem 1.35rem;margin-bottom:1.25rem;min-width:0;}'
        . 'body.portal-page .section-card:last-child{margin-bottom:0;}'
        . 'body.portal-page .section-card-title{font-family:\'Rajdhani\',sans-serif;font-size:1.1rem;font-weight:600;margin:0 0 1rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:.5rem;}'
        . 'body.portal-page .section-card-title a{font-size:.8rem;color:var(--cyber-accent);text-decoration:none;font-family:\'DM Sans\',sans-serif;white-space:nowrap;}'
        . 'body.portal-page .welcome-banner{background:linear-gradient(135deg,rgba(0,212,255,0.15),rgba(0,255,136,0.08));border:1px solid var(--cyber-border);border-radius:12px;padding:1.25rem 1.35rem;margin:0 0 1.25rem;position:relative;overflow:hidden;}'
        . 'body.portal-page .welcome-banner::before{content:\'\';position:absolute;right:-50px;top:-50px;width:200px;height:200px;background:radial-gradient(circle,rgba(0,212,255,0.15),transparent 70%);pointer-events:none;}'
        . 'body.portal-page .welcome-banner h3{margin:0 0 .35rem;}'
        . 'body.portal-page .item-card{background:rgba(10,22,40,.35);border:1px solid var(--cyber-border);border-radius:10px;padding:.9rem 1rem;margin-bottom:.65rem;display:flex;align-items:center;gap:.85rem;flex-wrap:nowrap;transition:border-color .2s;}'
        . 'body.portal-page .item-card:last-child{margin-bottom:0;}'
        . 'body.portal-page .item-card:hover{border-color:var(--cyber-accent);}'
        . 'body.portal-page .item-date{background:rgba(0,212,255,0.1);border:1px solid var(--cyber-border);border-radius:8px;padding:.45rem .65rem;text-align:center;min-width:48px;flex-shrink:0;}'
        . 'body.portal-page .item-date-day{font-family:\'Rajdhani\',sans-serif;font-size:1.25rem;font-weight:700;color:var(--cyber-accent);line-height:1;}'
        . 'body.portal-page .item-date-mon{font-size:.68rem;color:var(--cyber-muted);text-transform:uppercase;}'
        . 'body.portal-page .item-title{font-size:.9rem;font-weight:500;margin:0;}'
        . 'body.portal-page .item-meta{font-size:.78rem;color:var(--cyber-muted);margin-top:.15rem;}'
        . 'body.portal-page .item-status{margin-left:auto;font-size:.72rem;padding:.2rem .65rem;border-radius:4px;font-weight:600;white-space:nowrap;flex-shrink:0;}'
        . 'body.portal-page .status-paid{background:rgba(0,255,136,0.12);color:var(--cyber-green);border:1px solid rgba(0,255,136,0.25);}'
        . 'body.portal-page .status-free{background:rgba(0,212,255,0.12);color:var(--cyber-accent);border:1px solid rgba(0,212,255,0.25);}'
        . 'body.portal-page .status-pending{background:rgba(255,107,53,0.12);color:var(--cyber-orange);border:1px solid rgba(255,107,53,0.25);}'
        . 'body.portal-page .section-card .tx-row{display:flex;align-items:center;gap:.75rem;padding:.65rem 0;border-bottom:1px solid var(--cyber-border);margin:0;}'
        . 'body.portal-page .section-card .tx-row:last-child{border-bottom:none;padding-bottom:0;}'
        . 'body.portal-page .tx-icon{width:36px;height:36px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:.85rem;flex-shrink:0;}'
        . 'body.portal-page .tx-credit{background:rgba(0,255,136,0.1);color:var(--cyber-green);}'
        . 'body.portal-page .tx-debit{background:rgba(255,68,68,0.1);color:#ff4444;}'
        . 'body.portal-page .tx-desc{flex:1;min-width:0;}'
        . 'body.portal-page .tx-title{font-size:.85rem;margin:0;}'
        . 'body.portal-page .tx-date{font-size:.75rem;color:var(--cyber-muted);}'
        . 'body.portal-page .tx-amount{font-family:\'Rajdhani\',sans-serif;font-size:1rem;font-weight:700;flex-shrink:0;}'
        . 'body.portal-page .tx-amount.credit{color:var(--cyber-green);}'
        . 'body.portal-page .tx-amount.debit{color:#ff4444;}'
        . 'body.portal-page .notif-item{padding:.7rem 0;border-bottom:1px solid var(--cyber-border);display:flex;gap:.75rem;align-items:flex-start;margin:0;}'
        . 'body.portal-page .notif-item:last-child{border-bottom:none;padding-bottom:0;}'
        . 'body.portal-page .notif-dot-wrap{width:8px;height:8px;border-radius:50%;flex-shrink:0;margin-top:6px;}'
        . 'body.portal-page .notif-dot-wrap.unread{background:var(--cyber-accent);border:none;}'
        . 'body.portal-page .notif-dot-wrap.read{background:transparent;border:1px solid var(--cyber-border);}'
        . 'body.portal-page .notif-title{font-size:.85rem;margin:0;}'
        . 'body.portal-page .notif-time{font-size:.78rem;color:var(--cyber-muted);margin-top:2px;}'
        . 'body.portal-page .portal-empty{text-align:center;padding:1.5rem 1rem;color:var(--cyber-muted);font-size:.88rem;}'
        . 'body.portal-page .portal-empty i{display:block;font-size:2rem;opacity:.35;margin-bottom:.5rem;}'
        . 'body.portal-page .topbar-link{font-size:.85rem;color:var(--cyber-accent);text-decoration:none;padding:.4rem .9rem;border:1px solid var(--cyber-border);border-radius:6px;white-space:nowrap;}'
        . 'body.portal-page .topbar-link:hover{background:rgba(0,212,255,.08);}'
        . 'body.portal-page .notif-btn{position:relative;background:none;border:none;color:var(--cyber-muted);font-size:1.1rem;cursor:pointer;padding:.35rem;line-height:1;}'
        . 'body.portal-page .notif-dot{position:absolute;top:2px;right:2px;width:8px;height:8px;background:#ff4444;border-radius:50%;}'
        . 'body.portal-page .referral-input-row{display:flex;gap:.5rem;align-items:stretch;flex-wrap:wrap;}'
        . 'body.portal-page .referral-input-row input{flex:1 1 200px;min-width:0;}'
        . 'body.portal-page .referral-input-row .btn-cyber{flex-shrink:0;}'
        . 'body.portal-page .wallet-hero{background:linear-gradient(135deg,rgba(0,255,136,0.12),rgba(0,212,255,0.08));border:1px solid rgba(0,255,136,0.25);border-radius:16px;padding:clamp(1.25rem,4vw,2rem);margin-bottom:1.25rem;position:relative;overflow:hidden;}'
        . 'body.portal-page .wallet-balance-amount{font-family:\'Rajdhani\',sans-serif;font-size:clamp(2rem,8vw,3.5rem);font-weight:700;color:var(--cyber-green);line-height:1;}'
        . 'body.portal-page .wallet-stats{display:flex;gap:clamp(1rem,4vw,2rem);margin-top:1.25rem;flex-wrap:wrap;}'
        . 'body.portal-page .earn-card{background:var(--cyber-card);border:1px solid var(--cyber-border);border-radius:12px;padding:1.25rem;text-align:center;min-width:0;height:100%;}'
        . 'body.portal-page .section-card-header{padding:1rem 1.35rem;border-bottom:1px solid var(--cyber-border);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:.5rem;background:rgba(0,0,0,0.12);}'
        . 'body.portal-page .tx-table .tx-row{display:grid;grid-template-columns:40px minmax(0,2fr) minmax(0,1fr) minmax(0,1fr);align-items:center;padding:.85rem 1.35rem;border-bottom:1px solid rgba(0,212,255,0.06);gap:1rem;}'
        . 'body.portal-page .filter-tabs{display:flex;gap:.5rem;flex-wrap:wrap;}'
        . 'body.portal-page .filter-tab{padding:.35rem 1rem;border-radius:20px;font-size:.8rem;border:1px solid var(--cyber-border);color:var(--cyber-muted);text-decoration:none;}'
        . 'body.portal-page .filter-tab:hover,body.portal-page .filter-tab.active{background:var(--cyber-accent);color:var(--cyber-dark);border-color:var(--cyber-accent);}'
        . 'body.portal-page .w-stat{text-align:center;min-width:4.5rem;}'
        . 'body.portal-page .w-stat-val{font-family:\'Rajdhani\',sans-serif;font-size:1.5rem;font-weight:700;}'
        . 'body.portal-page .w-stat-label{font-size:.75rem;color:var(--cyber-muted);}'
        . 'body.portal-page .earn-icon{width:52px;height:52px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:1.3rem;margin:0 auto .75rem;}'
        . 'body.portal-page .earn-amount{font-family:\'Rajdhani\',sans-serif;font-size:1.6rem;font-weight:700;color:var(--cyber-green);}'
        . 'body.portal-page .earn-label{font-size:.8rem;color:var(--cyber-muted);}'
        . 'body.portal-page .badge-reason{font-size:.7rem;padding:2px 8px;border-radius:4px;background:rgba(0,212,255,0.1);color:var(--cyber-accent);border:1px solid rgba(0,212,255,0.2);}'
        . 'body.portal-page .redeem-card{background:linear-gradient(135deg,rgba(255,107,53,0.1),rgba(255,107,53,0.04));border:1px solid rgba(255,107,53,0.25);border-radius:12px;padding:1.35rem;}'
        . 'body.portal-page .wallet-balance-label{font-size:.85rem;color:var(--cyber-muted);}'
        . 'body.portal-page .wallet-balance-unit{font-size:1.2rem;font-weight:400;color:var(--cyber-muted);}'
        . 'body.portal-page .dashboard-stats{margin-bottom:1.25rem;}'
        . 'body.portal-page .dashboard-grid{align-items:flex-start;}'
        . 'body.portal-page .leader-my-rank{background:rgba(0,212,255,.1);border:1px solid var(--cyber-border);border-radius:10px;padding:.75rem 1rem;margin-bottom:1rem;font-size:.9rem;}'
        . 'body.portal-page .leader-podium-card{background:var(--cyber-card);border:1px solid var(--cyber-border);border-radius:12px;padding:1rem .75rem;text-align:center;min-height:140px;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;}'
        . 'body.portal-page .leader-podium-card.rank-1{border-color:rgba(255,209,102,.5);background:linear-gradient(180deg,rgba(255,209,102,.12),var(--cyber-card));min-height:165px;}'
        . 'body.portal-page .leader-podium-card.is-me,.body.portal-page .leader-table-row.is-me{box-shadow:0 0 0 1px rgba(0,212,255,.45);background:rgba(0,212,255,.06);}'
        . 'body.portal-page .leader-podium-medal{font-size:1.5rem;line-height:1;margin-bottom:.35rem;}'
        . 'body.portal-page .leader-podium-avatar,.body.portal-page .leader-row-avatar{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,var(--cyber-accent),var(--cyber-blue));color:var(--cyber-dark);font-weight:700;font-size:.85rem;display:inline-flex;align-items:center;justify-content:center;}'
        . 'body.portal-page .leader-podium-avatar{width:48px;height:48px;font-size:1rem;margin:.35rem 0;}'
        . 'body.portal-page .leader-podium-name{font-weight:600;font-size:.88rem;}'
        . 'body.portal-page .leader-podium-score{font-size:.78rem;color:var(--cyber-green);margin-top:.25rem;}'
        . 'body.portal-page .leader-table{display:flex;flex-direction:column;gap:0;}'
        . 'body.portal-page .leader-table-head,.body.portal-page .leader-table-row{display:grid;grid-template-columns:56px minmax(0,1.4fr) repeat(3,minmax(0,.75fr));gap:.65rem;align-items:center;padding:.65rem .5rem;}'
        . 'body.portal-page .leader-table-head{font-size:.72rem;text-transform:uppercase;letter-spacing:.06em;color:var(--cyber-muted);border-bottom:1px solid var(--cyber-border);padding-bottom:.75rem;}'
        . 'body.portal-page .leader-table-row{border-bottom:1px solid rgba(0,212,255,.08);font-size:.88rem;}'
        . 'body.portal-page .leader-table-row:last-child{border-bottom:none;}'
        . 'body.portal-page .leader-student{display:flex;align-items:center;gap:.5rem;min-width:0;}'
        . 'body.portal-page .portal-trainee-badge{font-size:.62rem;line-height:1.25;color:var(--cyber-muted);letter-spacing:.5px;margin-top:4px;max-width:100%;}'
        . 'body.portal-page .sidebar-logo .portal-trainee-badge{text-align:center;}'
        . '.data-table th{white-space:normal;}'
        . '.admin-action-btns{max-width:220px;}'
        . 'body.portal-page .leader-rank-num{font-family:\'Rajdhani\',sans-serif;font-weight:700;font-size:1rem;}'
        . 'body.portal-page .leader-metric{font-family:\'Rajdhani\',sans-serif;font-weight:600;}'
        . 'body.portal-page .leader-you-badge{font-size:.65rem;background:var(--cyber-accent);color:var(--cyber-dark);padding:2px 6px;border-radius:4px;margin-left:.35rem;font-weight:700;}'
        . '@media(max-width:767.98px){body.portal-page .leader-table-head{display:none;}body.portal-page .leader-table-row{grid-template-columns:44px 1fr;gap:.35rem .5rem;padding:.85rem .35rem;}body.portal-page .leader-table-row .leader-metric{grid-column:2;font-size:.8rem;color:var(--cyber-muted);}body.portal-page .leader-table-row .leader-metric::before{font-family:DM Sans,sans-serif;font-weight:400;margin-right:.35rem;color:var(--cyber-muted);}body.portal-page .leader-table-row .leader-metric:nth-child(3)::before{content:"NxL: ";}body.portal-page .leader-table-row .leader-metric:nth-child(4)::before{content:"Earned: ";}body.portal-page .leader-table-row .leader-metric:nth-child(5)::before{content:"Refs: ";}}'
        . '</style>' . "\n";
}

/** Portal-only responsive rules (sidebar drawer, mobile topbar). */
function renderPortalResponsiveStyles(): void
{
    static $done = false;
    if ($done) {
        return;
    }
    $done = true;
    echo '<style id="cybeorch-portal-responsive">'
        . '.sidebar-overlay{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:1035;opacity:0;visibility:hidden;transition:opacity .25s,visibility .25s;}'
        . '.sidebar-overlay.show{opacity:1;visibility:visible;}'
        . '.sidebar-toggle{display:none;align-items:center;justify-content:center;width:40px;height:40px;padding:0;border:1px solid var(--cyber-border);background:rgba(0,212,255,.08);color:var(--cyber-accent);border-radius:8px;cursor:pointer;flex-shrink:0;margin-right:.5rem;}'
        . '.sidebar-toggle:hover{background:rgba(0,212,255,.15);}'
        . '@media(max-width:991.98px){'
        . 'body.portal-page .sidebar{transform:translateX(-100%);transition:transform .25s ease;box-shadow:none;}'
        . 'body.portal-page .sidebar.open{transform:translateX(0);box-shadow:4px 0 24px rgba(0,0,0,.5);}'
        . 'body.portal-page .main{margin-left:0!important;width:100%!important;max-width:100%!important;}'
        . 'body.portal-page .topbar{padding:.65rem 1rem;flex-wrap:wrap;}'
        . 'body.portal-page .topbar-actions{width:auto!important;}'
        . 'body.portal-page .content{padding:1rem;}'
        . 'body.portal-page .sidebar-toggle{display:inline-flex;}'
        . 'body.portal-page .item-card{flex-wrap:wrap;}'
        . 'body.portal-page .item-status{margin-left:0;margin-top:.35rem;}'
        . '}'
        . '@media(max-width:767.98px){'
        . 'body.portal-page .content{padding:.85rem;}'
        . 'body.portal-page .section-card{padding:1rem;}'
        . 'body.portal-page .welcome-banner{padding:1rem;}'
        . 'body.portal-page .topbar-link{font-size:.8rem;padding:.35rem .65rem;}'
        . 'body.portal-page .referral-input-row .btn-cyber{width:100%;}'
        . '}'
        . '@media(min-width:992px){body.portal-page .sidebar{transform:none!important;}}'
        . '</style>' . "\n";
}
