<?php
declare(strict_types=1);

/**
 * Site-wide responsive CSS and user registration & trainee/admin portal mobile navigation.
 */

/** CYBEORCH-themed styling for all native select and Bootstrap .form-select fields. */
function renderFormSelectStyles(): void
{
    static $done = false;
    if ($done) {
        return;
    }
    $done = true;
    $chevron = "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23ffffff' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M2 5l6 6 6-6'/%3e%3c/svg%3e\")";
    echo '<style id="cybeorch-form-select">'
        . ':root{--cybeorch-select-bg:#0f1f3d;--cybeorch-select-border:#00bfff;--cybeorch-select-text:#ffffff;--cybeorch-select-highlight:#00bfff;}'
        . 'select,.form-select{background-color:var(--cybeorch-select-bg)!important;color:var(--cybeorch-select-text)!important;border:1px solid var(--cybeorch-select-border)!important;border-radius:6px!important;-webkit-appearance:none!important;appearance:none!important;}'
        . 'select option,.form-select option,select optgroup,.form-select optgroup{background-color:var(--cybeorch-select-bg)!important;color:var(--cybeorch-select-text)!important;}'
        . 'select option:checked,.form-select option:checked,select option:active,.form-select option:active{background:var(--cybeorch-select-highlight)!important;color:#fff!important;}'
        . 'select option:hover,.form-select option:hover{background:var(--cybeorch-select-highlight)!important;color:#fff!important;}'
        . 'select:focus,.form-select:focus,select:hover,.form-select:hover{background-color:var(--cybeorch-select-bg)!important;color:var(--cybeorch-select-text)!important;border-color:var(--cybeorch-select-border)!important;box-shadow:0 0 0 .2rem rgba(0,191,255,.25)!important;outline:none!important;}'
        . 'select:disabled,.form-select:disabled{background-color:#0a1628!important;color:#8aa0b8!important;border-color:rgba(0,191,255,.35)!important;opacity:.92;cursor:not-allowed;}'
        . '.form-select{background-image:' . $chevron . '!important;background-repeat:no-repeat!important;background-position:right .75rem center!important;background-size:16px 12px!important;padding-right:2.25rem!important;}'
        . '.form-select:focus,.form-select:hover{background-image:' . $chevron . '!important;}'
        . '.form-select-placeholder:has(option[value=""]:checked){color:#8ab4d4!important;}'
        . '.form-select-placeholder option[value=""]{color:#8ab4d4!important;}'
        . '.form-select-placeholder option:not([value=""]){color:#fff!important;}'
        . 'select:-webkit-autofill,select:-webkit-autofill:hover,select:-webkit-autofill:focus,.form-select:-webkit-autofill,.form-select:-webkit-autofill:hover,.form-select:-webkit-autofill:focus{-webkit-text-fill-color:#fff!important;-webkit-box-shadow:0 0 0 1000px #0f1f3d inset!important;box-shadow:0 0 0 1000px #0f1f3d inset!important;}'
        . '@-moz-document url-prefix(){select,.form-select{color-scheme:dark;}}'
        . '@media(forced-colors:active){select,.form-select{border:1px solid ButtonText!important;}}'
        . '</style>' . "\n";
}

function renderSiteResponsiveStyles(): void
{
    static $done = false;
    if ($done) {
        return;
    }
    $done = true;
    renderIconStyles();
    renderBrandStyles();
    echo '<style id="cybeorch-responsive">'
        . 'p,.hero-copy,.page-hero p,.service-card p,.about-card p,.ecosystem-item p,.webinar-desc,.career-card p,.auth-subtitle{color:#ffffff!important;}'
        . 'html{-webkit-text-size-adjust:100%;}'
        . 'html{overflow-x:clip;}'
        . 'body{overflow-x:clip;max-width:100vw;}'
        . 'img,video,iframe{max-width:100%;height:auto;}'
        . '.container,.container-fluid{padding-left:max(1rem,env(safe-area-inset-left));padding-right:max(1rem,env(safe-area-inset-right));}'
        . '.page-hero{padding:clamp(2rem,6vw,4rem) 0 clamp(1rem,3vw,2rem)!important;}'
        . '.page-hero p{padding-left:.5rem;padding-right:.5rem;}'
        . '.section{padding:clamp(2.5rem,5vw,5rem) 0!important;}'
        . '.section.pt-0{padding-top:0!important;}'
        . 'body:not(.portal-page) .content{padding:clamp(1rem,3vw,1.5rem)!important;}'
        . 'body:not(.portal-page) .topbar{padding:.75rem clamp(1rem,3vw,1.5rem)!important;flex-wrap:wrap;gap:.5rem;}'
        . 'body:not(.portal-page) .page-title{font-size:clamp(1.1rem,4vw,1.4rem)!important;}'
        . '@media(max-width:991.98px){body:not(.portal-page) .topbar-actions{width:100%;justify-content:flex-end;}}'
        . '.btn-primary-cyber,.btn-outline-cyber,.btn-cyber{max-width:100%;}'
        . '@media(max-width:767.98px){.btn-primary-cyber,.btn-outline-cyber,.btn-cyber{display:inline-flex;align-items:center;justify-content:center;}}'
        . '.footer .row{text-align:center;}'
        . '.footer .footer-links{margin-bottom:1.25rem;}'
        . '.footer .social-link{margin-bottom:.5rem;}'
        . '.project-card .btn-primary-cyber{max-width:100%;}'
        . '.hero-intro{padding:clamp(2rem,5vw,4rem) 0!important;}'
        . '.service-card,.about-card,.contact-card{margin-bottom:1rem;}'
        . '.cta-box{padding:clamp(1.5rem,4vw,3rem)!important;}'
        . '@media(max-width:767.98px){.btn-primary-cyber{display:inline-block;max-width:100%;}}'
        . '.stat-box{margin-bottom:1rem;}'
        . '.auth-container{padding:0 .25rem;}'
        . '.auth-card{padding:clamp(1.25rem,4vw,2.5rem)!important;}'
        . '.checkout-wrap,.payment-card{padding:1rem!important;}'
        . '.wallet-balance-amount{font-size:clamp(2.25rem,10vw,4rem)!important;}'
        . '.wallet-stats{gap:1rem!important;justify-content:space-between;}'
        . '.wallet-hero{padding:clamp(1.25rem,4vw,2rem)!important;}'
        . '.section-card-header{align-items:flex-start;gap:.75rem;}'
        . '@media(max-width:767.98px){body.portal-page .section-card-header{flex-direction:column;}}'
        . '.filter-tabs{width:100%;}'
        . '.item-card{flex-wrap:wrap;}'
        . '.item-status{margin-left:0!important;margin-top:.5rem;}'
        . '.admin-stat-grid,.stats-row{--bs-gutter-x:1rem;}'
        . '.table-responsive-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch;margin:0 -0.5rem;padding:0 .5rem;}'
        . '.table-responsive-wrap>table,.section-card-body .data-table{min-width:520px;}'
        . '.sidebar{transition:transform .3s ease;}'
        . '.sidebar-overlay{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:1035;opacity:0;visibility:hidden;transition:opacity .25s,visibility .25s;}'
        . '.sidebar-overlay.show{opacity:1;visibility:visible;}'
        . '.sidebar-toggle{display:none;align-items:center;justify-content:center;width:42px;height:42px;padding:0;border:1px solid var(--cyber-border);background:rgba(0,212,255,.08);color:var(--cyber-accent);border-radius:8px;cursor:pointer;flex-shrink:0;transition:background .2s;}'
        . '.sidebar-toggle:hover{background:rgba(0,212,255,.15);}'
        . '@media(max-width:991.98px){'
        . '.sidebar{transform:translateX(-100%);z-index:1040;}'
        . '.sidebar.open{transform:translateX(0);box-shadow:4px 0 24px rgba(0,0,0,.5);}'
        . '.main{margin-left:0!important;}'
        . '.sidebar-toggle{display:inline-flex;}'
        . '.section-card{overflow-x:auto;-webkit-overflow-scrolling:touch;}'
        . '.data-table{min-width:560px;}'
        . '}'
        . '@media(max-width:767.98px){'
        . '.hero{min-height:0!important;}'
        . '.hero-terminal{height:auto!important;max-height:none!important;}'
        . '.hero-terminal .hero-img{width:100%!important;height:auto!important;max-height:none!important;object-fit:contain!important;}'
        . '.hero-content{text-align:center;}'
        . '.hero-buttons{justify-content:center!important;flex-wrap:wrap;gap:.75rem;}'
        . '.hero-stats{justify-content:center!important;flex-wrap:wrap;gap:1rem!important;}'
        . '.hero-stats .stat-num{font-size:clamp(1.5rem,5vw,2rem)!important;}'
        . '.bootcamp-price{position:static!important;text-align:left!important;margin-bottom:.75rem;}'
        . '.bootcamp-header{padding:1.25rem!important;}'
        . '.bootcamp-header h3{font-size:1.2rem!important;}'
        . '.btn-outline-cyber{margin-left:0!important;display:block;width:100%;max-width:320px;margin:.75rem auto 0!important;}'
        . '.ecosystem-item{flex-direction:column;text-align:center;}'
        . '.ecosystem-item .icon{margin:0 auto;}'
        . '.project-card .btn-primary-cyber{width:100%;}'
        . '.tx-table-header{display:none!important;}'
        . '.tx-table .tx-row{display:flex!important;flex-wrap:wrap;align-items:flex-start!important;gap:.5rem .75rem;padding:1rem clamp(.75rem,3vw,1.5rem)!important;}'
        . '.tx-row .tx-icon{flex-shrink:0;}'
        . '.tx-row>div:nth-child(2){flex:1 1 calc(100% - 52px);min-width:0;}'
        . '.tx-row .tx-bal,.tx-row>div:nth-child(3){width:100%;}'
        . '.tx-row .tx-amount-credit,.tx-row .tx-amount-debit,.tx-row>div:last-child{width:100%;}'
        . '.tx-row .tx-bal::before{content:"Balance: ";color:var(--cyber-muted);font-size:.75rem;}'
        . '.tx-row .tx-amount-credit,.tx-row .tx-amount-debit{text-align:left!important;}'
        . '.tx-row .tx-amount-credit::before,.tx-row .tx-amount-debit::before{content:"Amount: ";color:var(--cyber-muted);font-size:.75rem;font-weight:400;font-family:DM Sans,sans-serif;}'
        . '}'
        . '@media(max-width:575.98px){'
        . '.earn-card{padding:1rem!important;}'
        . '.webinar-card,.bootcamp-card,.project-card{padding:1.15rem!important;}'
        . '.hero-subtitle{font-size:clamp(1rem,4vw,1.35rem)!important;}'
        . '.footer-bottom{font-size:.8rem;padding-left:1rem;padding-right:1rem;}'
        . '.col-6.col-md-3{width:50%;}'
        . '}'
        . '@media(min-width:992px){.sidebar{transform:none!important;}.sidebar-toggle{display:none!important;}}'
        . '.cybeorch-db-alert{background:rgba(255,107,53,0.15);border-bottom:1px solid rgba(255,107,53,0.4);color:#ffb899;padding:.75rem 0;font-size:.88rem;position:relative;z-index:1045;}'
        . '.cybeorch-db-alert .container{display:flex;align-items:center;justify-content:center;gap:.5rem;text-align:center;flex-wrap:wrap;}'
        . '.section-title{font-size:clamp(1.6rem,4.5vw,2.5rem)!important;}'
        . '.section-subtitle{padding-left:.75rem;padding-right:.75rem;}'
        . '.hero-title{font-size:clamp(2rem,8vw,4.5rem)!important;}'
        . '.hero-subtitle{font-size:clamp(1rem,4vw,1.35rem)!important;}'
        . '.row.g-4>[class*="col-"],.row.g-5>[class*="col-"]{margin-bottom:.5rem;}'
        . '.tech-slider{-webkit-mask-image:linear-gradient(90deg,transparent,#000 5%,#000 95%,transparent);mask-image:linear-gradient(90deg,transparent,#000 5%,#000 95%,transparent);}'
        . '.tech-slide-item{width:clamp(120px,28vw,150px);}'
        . '.tech-slide-card{padding:1rem .75rem!important;}'
        . '.tech-slide-logo{width:48px!important;height:48px!important;}'
        . '.tech-slider-track{gap:1rem;animation-duration:55s;}'
        . '.partner-card,.tech-slide-card,.enquiry-form,.contact-form,.f-card,.assignment-card{min-width:0;}'
        . '.assignment-card{padding:clamp(1.15rem,4vw,1.5rem)!important;}'
        . '.assignment-card .card-top{flex-wrap:wrap;gap:.5rem;}'
        . '.assignment-card .btn-primary-cyber{width:100%;max-width:100%;}'
        . '#interestModal .modal-dialog{margin:max(.75rem,env(safe-area-inset-top)) max(.75rem,env(safe-area-inset-right)) max(.75rem,env(safe-area-inset-bottom)) max(.75rem,env(safe-area-inset-left));}'
        . '#interestModal .modal-content{max-height:min(92vh,calc(100dvh - 2rem));overflow-y:auto;-webkit-overflow-scrolling:touch;}'
        . '#interestModal .modal-body{padding:clamp(1rem,4vw,1.5rem);}'
        . '#interestModal .row.g-3>[class*="col-"]{width:100%;}'
        . '.partner-logo{width:72px!important;height:72px!important;}'
        . '.project-cta{padding:clamp(2rem,5vw,3.5rem) 1.25rem!important;}'
        . '.project-cta-btns{display:flex;flex-direction:row!important;flex-wrap:nowrap!important;justify-content:center!important;align-items:center;gap:.75rem;}'
        . '.project-cta-btns .btn-primary-cyber,.project-cta-btns .btn-outline-cyber{width:auto!important;max-width:none!important;margin:0!important;white-space:nowrap;}'
        . '.enquiry-form,.contact-form,.contact-card{padding:clamp(1.25rem,4vw,2.5rem)!important;}'
        . '.form-select,.form-control{font-size:16px!important;}'
        . '@media(max-width:767.98px){.desk-features>.col-md-6,.desk-features>.col-md-4{flex:0 0 100%;max-width:100%;}.feature-card-body,.feature-card-head{padding:1rem!important;}.f-jump{flex-wrap:wrap;gap:.5rem!important;}.f-jump a{font-size:.8rem;padding:.4rem .65rem;}}'
        . '@media(max-width:767.98px){.network-grid .col-md-6,.network-grid .col-lg-4{flex:0 0 100%;max-width:100%;}}'
        . '.skill-tag{font-size:.75rem;padding:.3rem .6rem;}'
        . '.hero-intro .row{align-items:center!important;}'
        . '.hero-terminal{aspect-ratio:unset!important;overflow:visible!important;}'
        . '.hero-terminal img,.hero-img{max-width:100%!important;width:100%!important;height:auto!important;max-height:none!important;display:block!important;}'
        . '.footer-logo img{max-width:220px;height:auto;}'
        . '.contact-info-card,.info-card{padding:1.15rem!important;}'
        . '@media(max-width:991.98px){'
        . '.hero .row{flex-direction:column-reverse;}'
        . '.hero-content{text-align:center;padding-top:1.5rem;}'
        . '}'
        . '@media(max-width:767.98px){'
        . '.tech-slide-item{width:130px;}'
        . '.partner-card{padding:1.5rem 1rem!important;}'
        . '.footer .col-6{width:50%;}'
        . '.footer .col-lg-4{text-align:center;}'
        . '.footer .social-link{margin:.25rem;}'
        . '.service-card,.solution-card,.about-card{padding:1.5rem!important;}'
        . '.auth-split{display:block!important;}'
        . '.payment-row{flex-direction:column;}'
        . '}'
        . '@media(max-width:575.98px){'
        . '.footer .col-6{width:100%;}'
        . '.tech-slide-name{font-size:.85rem;}'
        . '.page-hero h1{font-size:clamp(1.75rem,7vw,2.5rem)!important;}'
        . '.btn-primary-cyber,.btn-outline-cyber{padding:.75rem 1.25rem;font-size:.95rem;}'
        . '.step-list li{flex-direction:column;text-align:center;gap:.5rem;}'
        . '.step-num{margin:0 auto;}'
        . '.step-content{text-align:center;}'
        . '.project-cta-btns .btn-primary-cyber,.project-cta-btns .btn-outline-cyber{min-width:140px;padding:.75rem 1rem!important;font-size:.9rem;}'
        . '}'
        . '@media(min-width:768px) and (max-width:1024px){'
        . '.tech-slide-item{width:140px;}'
        . '.partner-card{padding:1.75rem 1.25rem;}'
        . '.section{padding:3.5rem 0!important;}'
        . '}'
        . '/* Scoped responsive helpers — do not override Bootstrap column widths on tablet/desktop */'
        . '.webinar-card,.bootcamp-card,.project-card,.f-card,.lp-card,.freelance-card,.assignment-card,.service-image-card,.card-panel,.section-card,.stat-card,.program-funnel-card{min-width:0;}'
        . 'img,video,canvas,iframe,svg{max-width:100%;height:auto;}'
        . 'h1,h2,h3,h4,h5,h6,p,.webinar-title,.lp-card-title,.section-title{overflow-wrap:break-word;}'
        . '.table-responsive,.table-responsive-wrap,.cy-table-scroll{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch;}'
        . '.table-responsive>.table,.table-responsive-wrap>table,.cy-table-scroll>table{width:100%;}'
        . '.table-responsive-wrap>table,.cy-table-scroll>table,.section-card-body .data-table{min-width:520px;}'
        . '.webinar-meta,.lp-meta,.project-meta{display:flex;flex-wrap:nowrap;gap:.75rem 1rem;}'
        . '.webinar-meta span,.lp-meta span,.project-meta span{white-space:nowrap;}'
        . '@media(max-width:767.98px){.webinar-meta,.lp-meta,.project-meta{flex-wrap:wrap;}}'
        . '@media(max-width:991.98px){'
        . '.lp-detail-hero .hero-banner{min-height:160px!important;}'
        . '.lp-detail-hero .hero-body{padding:1.25rem!important;}'
        . '.admin-toolbar{flex-direction:column;align-items:stretch!important;}'
        . '.admin-search-form{max-width:100%!important;}'
        . '.detail-grid{grid-template-columns:1fr!important;}'
        . '}'
        . '@media(max-width:767.98px){'
        . '.form-control,.form-select,.input-group{width:100%;max-width:100%;}'
        . '.checkout-wrap,.payment-card,.secure-payment-wrap,.enquiry-form,.contact-form,.auth-card,.form-card-body{padding:1rem!important;}'
        . '.btn-primary-cyber,.btn-outline-cyber,.btn-cyber,.btn-submit,.btn-nav-login,.btn-nav-register{min-height:44px;}'
        . '.lp-card-actions{flex-direction:column;align-items:stretch;}'
        . '.lp-card-actions .btn-primary-cyber,.lp-card-actions .btn-outline-lp{width:100%;}'
        . '.project-cta-btns{flex-direction:column;align-items:center;}'
        . '.project-cta-btns .btn-primary-cyber,.project-cta-btns .btn-outline-cyber{width:100%;max-width:320px;margin:.25rem 0!important;}'
        . '.program-funnel-card{margin-left:.75rem;margin-right:.75rem;}'
        . '.funnel-tier{flex:1 1 100%;}'
        . '.footer .col-md-6.text-md-end{margin-top:.75rem;}'
        . '.auth-reg-modal-dialog,.auth-reg-popup-inner,.cybeorch-reg-card,.webinar-closing-soon-card{max-width:calc(100vw - 1.5rem)!important;max-height:min(92dvh,calc(100vh - 1rem));overflow-y:auto;}'
        . '.modal-dialog{max-width:calc(100vw - 1.5rem);}'
        . '.modal-content{max-height:min(92dvh,calc(100vh - 2rem));overflow-y:auto;}'
        . '}'
        . '@media(max-width:575.98px){'
        . '.hero-buttons .btn-primary-cyber,.hero-buttons .btn-outline-cyber{width:100%;max-width:320px;}'
        . '.webinar-lightbox-close{width:40px;height:40px;font-size:1.35rem;}'
        . '.cybeorch-reg-card{padding:1rem!important;border-radius:16px;}'
        . '}'
        . '@supports(padding:max(0px)){.footer{padding-bottom:max(1.5rem,env(safe-area-inset-bottom));}}'
        . '</style>' . "\n";
    renderFormSelectStyles();
}

function renderStudentPortalNavScript(): void
{
    echo '<script id="cybeorch-portal-nav">'
        . 'document.addEventListener("DOMContentLoaded",function(){'
        . 'var sb=document.querySelector(".sidebar");'
        . 'if(!sb)return;'
        . 'var ov=document.querySelector(".sidebar-overlay");'
        . 'if(!ov){ov=document.createElement("div");ov.className="sidebar-overlay";ov.setAttribute("aria-hidden","true");document.body.appendChild(ov);}'
        . 'function closeMenu(){sb.classList.remove("open");ov.classList.remove("show");document.body.style.overflow="";}'
        . 'function openMenu(){sb.classList.add("open");ov.classList.add("show");document.body.style.overflow="hidden";}'
        . 'ov.addEventListener("click",closeMenu);'
        . 'sb.querySelectorAll("a").forEach(function(a){a.addEventListener("click",function(){if(window.innerWidth<992)closeMenu();});});'
        . 'function injectToggle(){'
        . 'var tb=document.querySelector(".main .topbar");'
        . 'if(!tb||document.getElementById("sidebarToggle"))return;'
        . 'var btn=document.createElement("button");'
        . 'btn.type="button";btn.id="sidebarToggle";btn.className="sidebar-toggle";'
        . 'btn.innerHTML="<i class=\\"fas fa-bars\\"></i>";'
        . 'btn.setAttribute("aria-label","Open navigation menu");'
        . 'btn.addEventListener("click",function(e){e.stopPropagation();sb.classList.contains("open")?closeMenu():openMenu();});'
        . 'if(tb.firstChild)tb.insertBefore(btn,tb.firstChild);else tb.appendChild(btn);'
        . '}'
        . 'injectToggle();'
        . 'window.addEventListener("resize",function(){if(window.innerWidth>=992)closeMenu();});'
        . 'document.addEventListener("keydown",function(e){if(e.key==="Escape")closeMenu();});'
        . '});'
        . '</script>' . "\n";
}
